// <auto-generated />
#nullable enable

// Сгенерировано tools/gen_block_catalog.py из schematics/Med_*/*.json.
// Не редактируйте вручную: правьте генератор схематиков и перезапустите скрипт.
//
// Схематиков: 36, блоков всего: 255, максимум блоков на перевязку: 9.
// Все блоки - куб (UnityEngine.PrimitiveType.Cube) с флагом Visible:
// повязка видна, но не имеет коллизии, поэтому ни во что не упирается.

using System.Collections.Generic;
using UnityEngine;

namespace MainCore.Medical.Visuals
{
    /// <summary>Один блок перевязки: куб с цветом, позицией и размером.</summary>
    public readonly struct WoundBlock
    {
        public WoundBlock(Vector3 position, Vector3 eulerAngles, Vector3 scale, Color color)
        {
            Position = position;
            EulerAngles = eulerAngles;
            Scale = scale;
            Color = color;
        }

        /// <summary>Смещение относительно точки крепления перевязки.</summary>
        public Vector3 Position { get; }

        /// <summary>Доворот блока в градусах.</summary>
        public Vector3 EulerAngles { get; }

        /// <summary>Размер куба в метрах.</summary>
        public Vector3 Scale { get; }

        public Color Color { get; }
    }

    /// <summary>
    /// Геометрия всех перевязок в виде обычных примитивов.
    /// Раньше это были схематики ProjectMER, но плагин грузит EXILED, а ProjectMER -
    /// LabAPI: сборку, загруженную из байтов, нельзя найти по имени, поэтому любой
    /// вызов в ProjectMER падал с FileNotFoundException ещё до первой строки метода.
    /// Собственные примитивы убирают зависимость целиком.
    /// </summary>
    public static class WoundBlockCatalog
    {
        /// <summary>Максимум блоков в одной перевязке - для оценки сетевой нагрузки.</summary>
        public const int MaxBlocksPerDressing = 9;

        private static readonly Dictionary<string, WoundBlock[]> Dressings = new()
        {
            ["Med_Bandage_Arm_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.04565f, 0f, 0.03717f), new Vector3(0f, 45f, 0f), new Vector3(0.02775f, 0.02775f, 0.02775f), new Color(0.82353f, 0.78431f, 0.6902f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.01586f, 0.0072f, 0.0866f), new Vector3(0f, 0f, 0f), new Vector3(0.03806f, 0.0558f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.04965f, 0.0018f, 0.02758f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.045f, 0.04902f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.01269f, -0.0765f, 0.0806f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.081f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Bandage_Arm_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.04565f, 0f, 0.03717f), new Vector3(0f, 45f, 0f), new Vector3(0.02775f, 0.02775f, 0.02775f), new Color(0.89412f, 0.86275f, 0.78824f, 1f)),
            },

            ["Med_Bandage_Arm_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.04565f, 0f, 0.03717f), new Vector3(0f, 45f, 0f), new Vector3(0.02775f, 0.02775f, 0.02775f), new Color(0.5451f, 0.50196f, 0.41176f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.01427f, 0.0045f, 0.0856f), new Vector3(0f, 0f, 0f), new Vector3(0.03172f, 0.045f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.04865f, 0.0108f, 0.02298f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0378f, 0.04596f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Bandage_Head_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0728f, 0f, 0.04556f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.82353f, 0.78431f, 0.6902f, 1f)),
                // Strap_Crown
                new WoundBlock(new Vector3(0f, 0.1218f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.08684f, 0.014f, 0.2025f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.02672f, 0.0056f, 0.10525f), new Vector3(0f, 0f, 0f), new Vector3(0.06413f, 0.0434f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0768f, 0.0014f, 0.03429f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.035f, 0.06096f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02138f, -0.0595f, 0.09925f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.063f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Bandage_Head_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0728f, 0f, 0.04556f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.89412f, 0.86275f, 0.78824f, 1f)),
                // Strap_Crown
                new WoundBlock(new Vector3(0f, 0.1218f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.08684f, 0.014f, 0.2025f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
            },

            ["Med_Bandage_Head_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0728f, 0f, 0.04556f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.5451f, 0.50196f, 0.41176f, 1f)),
                // Strap_Crown
                new WoundBlock(new Vector3(0f, 0.1218f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.08684f, 0.014f, 0.2025f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02405f, 0.0035f, 0.10425f), new Vector3(0f, 0f, 0f), new Vector3(0.05344f, 0.035f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0758f, 0.0084f, 0.02857f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0294f, 0.05715f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Bandage_Leg_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0828f, 0f, 0.04559f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.82353f, 0.78431f, 0.6902f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.03072f, 0.0088f, 0.1053f), new Vector3(0f, 0f, 0f), new Vector3(0.07373f, 0.0682f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0868f, 0.0022f, 0.03431f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.055f, 0.06099f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02458f, -0.0935f, 0.0993f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.099f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Bandage_Leg_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0828f, 0f, 0.04559f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.89412f, 0.86275f, 0.78824f, 1f)),
            },

            ["Med_Bandage_Leg_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.0828f, 0f, 0.04559f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.5451f, 0.50196f, 0.41176f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02765f, 0.0055f, 0.1043f), new Vector3(0f, 0f, 0f), new Vector3(0.06144f, 0.055f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0858f, 0.0132f, 0.02859f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0462f, 0.05718f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Bandage_Torso_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.18535f, 0f, 0.05144f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.82353f, 0.78431f, 0.6902f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.07174f, 0.012f, 0.1183f), new Vector3(0f, 0f, 0f), new Vector3(0.17218f, 0.093f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.18935f, 0.003f, 0.03899f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.075f, 0.06931f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.05739f, -0.1275f, 0.1123f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.135f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Bandage_Torso_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.18535f, 0f, 0.05144f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.89412f, 0.86275f, 0.78824f, 1f)),
            },

            ["Med_Bandage_Torso_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Knot
                new WoundBlock(new Vector3(0.18535f, 0f, 0.05144f), new Vector3(0f, 45f, 0f), new Vector3(0.03f, 0.03f, 0.03f), new Color(0.5451f, 0.50196f, 0.41176f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.06457f, 0.0075f, 0.1173f), new Vector3(0f, 0f, 0f), new Vector3(0.14348f, 0.075f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.18835f, 0.018f, 0.03249f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.063f, 0.06498f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Burn_Arm_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0162f, 0.0926f), new Vector3(0f, 0f, 0f), new Vector3(0.04362f, 0.045f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.01586f, 0.0072f, 0.0866f), new Vector3(0f, 0f, 0f), new Vector3(0.03806f, 0.0558f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.04965f, 0.0018f, 0.02758f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.045f, 0.04902f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.01269f, -0.0765f, 0.0806f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.081f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Burn_Arm_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0162f, 0.0926f), new Vector3(0f, 0f, 0f), new Vector3(0.04362f, 0.045f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
            },

            ["Med_Burn_Arm_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.09f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.09f, 0.1652f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0162f, 0.0926f), new Vector3(0f, 0f, 0f), new Vector3(0.04362f, 0.045f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.01427f, 0.0045f, 0.0856f), new Vector3(0f, 0f, 0f), new Vector3(0.03172f, 0.045f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.04865f, 0.0108f, 0.02298f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0378f, 0.04596f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Burn_Head_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0126f, 0.11125f), new Vector3(0f, 0f, 0f), new Vector3(0.07348f, 0.035f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.02672f, 0.0056f, 0.10525f), new Vector3(0f, 0f, 0f), new Vector3(0.06413f, 0.0434f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0768f, 0.0014f, 0.03429f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.035f, 0.06096f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02138f, -0.0595f, 0.09925f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.063f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Burn_Head_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0126f, 0.11125f), new Vector3(0f, 0f, 0f), new Vector3(0.07348f, 0.035f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
            },

            ["Med_Burn_Head_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.10125f), new Vector3(0f, 0f, 0f), new Vector3(0.1456f, 0.07f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0728f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.07f, 0.2025f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0126f, 0.11125f), new Vector3(0f, 0f, 0f), new Vector3(0.07348f, 0.035f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02405f, 0.0035f, 0.10425f), new Vector3(0f, 0f, 0f), new Vector3(0.05344f, 0.035f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0758f, 0.0084f, 0.02857f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0294f, 0.05715f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Burn_Leg_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0198f, 0.1113f), new Vector3(0f, 0f, 0f), new Vector3(0.08448f, 0.055f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.03072f, 0.0088f, 0.1053f), new Vector3(0f, 0f, 0f), new Vector3(0.07373f, 0.0682f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0868f, 0.0022f, 0.03431f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.055f, 0.06099f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02458f, -0.0935f, 0.0993f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.099f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Burn_Leg_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0198f, 0.1113f), new Vector3(0f, 0f, 0f), new Vector3(0.08448f, 0.055f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
            },

            ["Med_Burn_Leg_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.11f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.11f, 0.2026f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.0198f, 0.1113f), new Vector3(0f, 0f, 0f), new Vector3(0.08448f, 0.055f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02765f, 0.0055f, 0.1043f), new Vector3(0f, 0f, 0f), new Vector3(0.06144f, 0.055f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0858f, 0.0132f, 0.02859f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0462f, 0.05718f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Burn_Torso_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.027f, 0.1243f), new Vector3(0f, 0f, 0f), new Vector3(0.19729f, 0.075f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.07174f, 0.012f, 0.1183f), new Vector3(0f, 0f, 0f), new Vector3(0.17218f, 0.093f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.18935f, 0.003f, 0.03899f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.075f, 0.06931f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.05739f, -0.1275f, 0.1123f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.135f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Burn_Torso_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.95294f, 0.93725f, 0.89412f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.027f, 0.1243f), new Vector3(0f, 0f, 0f), new Vector3(0.19729f, 0.075f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
            },

            ["Med_Burn_Torso_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1143f), new Vector3(0f, 0f, 0f), new Vector3(0.3707f, 0.15f, 0.014f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.18535f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.15f, 0.2286f), new Color(0.6549f, 0.61176f, 0.51765f, 1f)),
                // Pad_Front
                new WoundBlock(new Vector3(0f, 0.027f, 0.1243f), new Vector3(0f, 0f, 0f), new Vector3(0.19729f, 0.075f, 0.014f), new Color(0.9098f, 0.87843f, 0.80784f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.06457f, 0.0075f, 0.1173f), new Vector3(0f, 0f, 0f), new Vector3(0.14348f, 0.075f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.18835f, 0.018f, 0.03249f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.063f, 0.06498f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Splint_Arm_Blood"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.01586f, 0.0024f, 0.0866f), new Vector3(0f, 0f, 0f), new Vector3(0.03806f, 0.0186f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.04965f, 0.0006f, 0.02758f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.015f, 0.04902f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.01269f, -0.0255f, 0.0806f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.027f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Splint_Arm_Clean"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
            },

            ["Med_Splint_Arm_Dirty"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.05365f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.2f, 0.0766f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.064f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.064f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.1113f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.01427f, 0.0015f, 0.0856f), new Vector3(0f, 0f, 0f), new Vector3(0.03172f, 0.015f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.04865f, 0.0036f, 0.02298f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0126f, 0.04596f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Splint_Leg_Blood"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.86275f, 0.82745f, 0.7451f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.03072f, 0.0024f, 0.1053f), new Vector3(0f, 0f, 0f), new Vector3(0.07373f, 0.0186f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0868f, 0.0006f, 0.03431f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.015f, 0.06099f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02458f, -0.0255f, 0.0993f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.027f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Splint_Leg_Clean"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.92941f, 0.90588f, 0.85098f, 1f)),
            },

            ["Med_Splint_Leg_Dirty"] = new[]
            {
                // Rail_Left
                new WoundBlock(new Vector3(-0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Rail_Right
                new WoundBlock(new Vector3(0.0908f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.26f, 0.0953f), new Color(0.61176f, 0.48235f, 0.30588f, 1f)),
                // Strap_Upper_Front
                new WoundBlock(new Vector3(0f, 0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Upper_Back
                new WoundBlock(new Vector3(0f, 0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Lower_Front
                new WoundBlock(new Vector3(0f, -0.0832f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Strap_Lower_Back
                new WoundBlock(new Vector3(0f, -0.0832f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1856f, 0.03f, 0.014f), new Color(0.60392f, 0.56078f, 0.46275f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02765f, 0.0015f, 0.1043f), new Vector3(0f, 0f, 0f), new Vector3(0.06144f, 0.015f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0858f, 0.0036f, 0.02859f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0126f, 0.05718f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Tourniquet_Arm_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.06365f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.05565f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.01586f, 0.0036f, 0.0866f), new Vector3(0f, 0f, 0f), new Vector3(0.03806f, 0.0279f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.04965f, 0.0009f, 0.02758f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.0225f, 0.04902f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.01269f, -0.03825f, 0.0806f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.0405f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Tourniquet_Arm_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.06365f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.05565f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
            },

            ["Med_Tourniquet_Arm_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.0826f), new Vector3(0f, 0f, 0f), new Vector3(0.0913f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.04565f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.1652f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.06365f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.05565f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.01427f, 0.00225f, 0.0856f), new Vector3(0f, 0f, 0f), new Vector3(0.03172f, 0.0225f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.04865f, 0.0054f, 0.02298f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0189f, 0.04596f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },

            ["Med_Tourniquet_Leg_Blood"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.1008f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.0928f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
                // Blood_Soak_Front
                new WoundBlock(new Vector3(0.03072f, 0.0036f, 0.1053f), new Vector3(0f, 0f, 0f), new Vector3(0.07373f, 0.0279f, 0.005f), new Color(0.55686f, 0.10588f, 0.07843f, 1f)),
                // Blood_Soak_Side
                new WoundBlock(new Vector3(0.0868f, 0.0009f, 0.03431f), new Vector3(0f, 0f, 0f), new Vector3(0.005f, 0.0225f, 0.06099f), new Color(0.49412f, 0.0902f, 0.07059f, 1f)),
                // Blood_Drip
                new WoundBlock(new Vector3(0.02458f, -0.03825f, 0.0993f), new Vector3(0f, 0f, 0f), new Vector3(0.016f, 0.0405f, 0.005f), new Color(0.43529f, 0.07451f, 0.05882f, 1f)),
            },

            ["Med_Tourniquet_Leg_Clean"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.1008f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.0928f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
            },

            ["Med_Tourniquet_Leg_Dirty"] = new[]
            {
                // Band_Front
                new WoundBlock(new Vector3(0f, 0f, 0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Back
                new WoundBlock(new Vector3(0f, 0f, -0.1013f), new Vector3(0f, 0f, 0f), new Vector3(0.1656f, 0.045f, 0.014f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Left
                new WoundBlock(new Vector3(-0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Band_Right
                new WoundBlock(new Vector3(0.0828f, 0f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.014f, 0.045f, 0.2026f), new Color(0.22745f, 0.22745f, 0.22745f, 1f)),
                // Windlass
                new WoundBlock(new Vector3(0.1008f, 0f, 0f), new Vector3(0f, 0f, 25f), new Vector3(0.07f, 0.014f, 0.014f), new Color(0.41961f, 0.2902f, 0.16471f, 1f)),
                // Windlass_Clip
                new WoundBlock(new Vector3(0.0928f, -0.028f, 0f), new Vector3(0f, 0f, 0f), new Vector3(0.02f, 0.02f, 0.016f), new Color(0.16471f, 0.16471f, 0.16471f, 1f)),
                // Stain_Front
                new WoundBlock(new Vector3(0.02765f, 0.00225f, 0.1043f), new Vector3(0f, 0f, 0f), new Vector3(0.06144f, 0.0225f, 0.004f), new Color(0.43137f, 0.39216f, 0.31373f, 1f)),
                // Stain_Side
                new WoundBlock(new Vector3(-0.0858f, 0.0054f, 0.02859f), new Vector3(0f, 0f, 0f), new Vector3(0.004f, 0.0189f, 0.05718f), new Color(0.46667f, 0.41176f, 0.3098f, 1f)),
            },
        };

        /// <summary>Сколько перевязок в каталоге.</summary>
        public static int Count => Dressings.Count;

        /// <summary>Все известные имена перевязок.</summary>
        public static IEnumerable<string> Names => Dressings.Keys;

        /// <summary>Возвращает блоки перевязки. Пустой массив - имени нет в каталоге.</summary>
        public static WoundBlock[] Get(string name) =>
            Dressings.TryGetValue(name, out WoundBlock[]? blocks) ? blocks : System.Array.Empty<WoundBlock>();

        public static bool Has(string name) => Dressings.ContainsKey(name);
    }
}
